- name: update apache
  pkgng: name=apache24 cached=no pkgsite="{{repo.name}}" state=present
  register: result
- name: restart apache
  service: name=apache{{apache.version}} enabled=yes state=restarted
  when: result|changed


